namespace php {
extern Variant xml_parser_create;
extern Variant xml_parser_create_ns;
extern Variant xml_set_object;
extern Variant xml_set_element_handler;
extern Variant xml_set_character_data_handler;
extern Variant xml_set_processing_instruction_handler;
extern Variant xml_set_default_handler;
extern Variant xml_set_unparsed_entity_decl_handler;
extern Variant xml_set_notation_decl_handler;
extern Variant xml_set_external_entity_ref_handler;
extern Variant xml_set_start_namespace_decl_handler;
extern Variant xml_set_end_namespace_decl_handler;
extern Variant xml_parse;
extern Variant xml_parse_into_struct;
extern Variant xml_get_error_code;
extern Variant xml_error_string;
extern Variant xml_get_current_line_number;
extern Variant xml_get_current_column_number;
extern Variant xml_get_current_byte_index;
extern Variant xml_parser_free;
extern Variant xml_parser_set_option;
extern Variant xml_parser_get_option;
}
