namespace php {
class Redis {
  private:
    Variant _this;
  public:
    Redis(const std::initializer_list<Variant> &args);
    Variant _compress(const std::initializer_list<Variant> &args);
    Variant _uncompress(const std::initializer_list<Variant> &args);
    Variant _prefix(const std::initializer_list<Variant> &args);
    Variant _serialize(const std::initializer_list<Variant> &args);
    Variant _unserialize(const std::initializer_list<Variant> &args);
    Variant _pack(const std::initializer_list<Variant> &args);
    Variant _unpack(const std::initializer_list<Variant> &args);
    Variant acl(const std::initializer_list<Variant> &args);
    Variant append(const std::initializer_list<Variant> &args);
    Variant auth(const std::initializer_list<Variant> &args);
    Variant bgSave();
    Variant bgrewriteaof();
    Variant bitcount(const std::initializer_list<Variant> &args);
    Variant bitop(const std::initializer_list<Variant> &args);
    Variant bitpos(const std::initializer_list<Variant> &args);
    Variant blPop(const std::initializer_list<Variant> &args);
    Variant brPop(const std::initializer_list<Variant> &args);
    Variant brpoplpush(const std::initializer_list<Variant> &args);
    Variant bzPopMax(const std::initializer_list<Variant> &args);
    Variant bzPopMin(const std::initializer_list<Variant> &args);
    Variant bzmpop(const std::initializer_list<Variant> &args);
    Variant zmpop(const std::initializer_list<Variant> &args);
    Variant blmpop(const std::initializer_list<Variant> &args);
    Variant lmpop(const std::initializer_list<Variant> &args);
    Variant clearLastError();
    Variant client(const std::initializer_list<Variant> &args);
    Variant close();
    Variant command(const std::initializer_list<Variant> &args);
    Variant config(const std::initializer_list<Variant> &args);
    Variant connect(const std::initializer_list<Variant> &args);
    Variant copy(const std::initializer_list<Variant> &args);
    Variant dbSize();
    Variant debug(const std::initializer_list<Variant> &args);
    Variant decr(const std::initializer_list<Variant> &args);
    Variant decrBy(const std::initializer_list<Variant> &args);
    Variant del(const std::initializer_list<Variant> &args);
    Variant _delete(const std::initializer_list<Variant> &args);
    Variant discard();
    Variant dump(const std::initializer_list<Variant> &args);
    Variant echo(const std::initializer_list<Variant> &args);
    Variant eval(const std::initializer_list<Variant> &args);
    Variant eval_ro(const std::initializer_list<Variant> &args);
    Variant evalsha(const std::initializer_list<Variant> &args);
    Variant evalsha_ro(const std::initializer_list<Variant> &args);
    Variant exec();
    Variant exists(const std::initializer_list<Variant> &args);
    Variant expire(const std::initializer_list<Variant> &args);
    Variant expireAt(const std::initializer_list<Variant> &args);
    Variant failover(const std::initializer_list<Variant> &args);
    Variant expiretime(const std::initializer_list<Variant> &args);
    Variant pexpiretime(const std::initializer_list<Variant> &args);
    Variant fcall(const std::initializer_list<Variant> &args);
    Variant fcall_ro(const std::initializer_list<Variant> &args);
    Variant flushAll(const std::initializer_list<Variant> &args);
    Variant flushDB(const std::initializer_list<Variant> &args);
    Variant function(const std::initializer_list<Variant> &args);
    Variant geoadd(const std::initializer_list<Variant> &args);
    Variant geodist(const std::initializer_list<Variant> &args);
    Variant geohash(const std::initializer_list<Variant> &args);
    Variant geopos(const std::initializer_list<Variant> &args);
    Variant georadius(const std::initializer_list<Variant> &args);
    Variant georadius_ro(const std::initializer_list<Variant> &args);
    Variant georadiusbymember(const std::initializer_list<Variant> &args);
    Variant georadiusbymember_ro(const std::initializer_list<Variant> &args);
    Variant geosearch(const std::initializer_list<Variant> &args);
    Variant geosearchstore(const std::initializer_list<Variant> &args);
    Variant get(const std::initializer_list<Variant> &args);
    Variant getAuth();
    Variant getBit(const std::initializer_list<Variant> &args);
    Variant getEx(const std::initializer_list<Variant> &args);
    Variant getDBNum();
    Variant getDel(const std::initializer_list<Variant> &args);
    Variant getHost();
    Variant getLastError();
    Variant getMode();
    Variant getOption(const std::initializer_list<Variant> &args);
    Variant getPersistentID();
    Variant getPort();
    Variant getRange(const std::initializer_list<Variant> &args);
    Variant lcs(const std::initializer_list<Variant> &args);
    Variant getReadTimeout();
    Variant getset(const std::initializer_list<Variant> &args);
    Variant getTimeout();
    Variant getTransferredBytes();
    Variant clearTransferredBytes();
    Variant hDel(const std::initializer_list<Variant> &args);
    Variant hExists(const std::initializer_list<Variant> &args);
    Variant hGet(const std::initializer_list<Variant> &args);
    Variant hGetAll(const std::initializer_list<Variant> &args);
    Variant hIncrBy(const std::initializer_list<Variant> &args);
    Variant hIncrByFloat(const std::initializer_list<Variant> &args);
    Variant hKeys(const std::initializer_list<Variant> &args);
    Variant hLen(const std::initializer_list<Variant> &args);
    Variant hMget(const std::initializer_list<Variant> &args);
    Variant hMset(const std::initializer_list<Variant> &args);
    Variant hRandField(const std::initializer_list<Variant> &args);
    Variant hSet(const std::initializer_list<Variant> &args);
    Variant hSetNx(const std::initializer_list<Variant> &args);
    Variant hStrLen(const std::initializer_list<Variant> &args);
    Variant hVals(const std::initializer_list<Variant> &args);
    Variant hscan(const std::initializer_list<Variant> &args);
    Variant incr(const std::initializer_list<Variant> &args);
    Variant incrBy(const std::initializer_list<Variant> &args);
    Variant incrByFloat(const std::initializer_list<Variant> &args);
    Variant info(const std::initializer_list<Variant> &args);
    Variant isConnected();
    Variant keys(const std::initializer_list<Variant> &args);
    Variant lInsert(const std::initializer_list<Variant> &args);
    Variant lLen(const std::initializer_list<Variant> &args);
    Variant lMove(const std::initializer_list<Variant> &args);
    Variant blmove(const std::initializer_list<Variant> &args);
    Variant lPop(const std::initializer_list<Variant> &args);
    Variant lPos(const std::initializer_list<Variant> &args);
    Variant lPush(const std::initializer_list<Variant> &args);
    Variant rPush(const std::initializer_list<Variant> &args);
    Variant lPushx(const std::initializer_list<Variant> &args);
    Variant rPushx(const std::initializer_list<Variant> &args);
    Variant lSet(const std::initializer_list<Variant> &args);
    Variant lastSave();
    Variant lindex(const std::initializer_list<Variant> &args);
    Variant lrange(const std::initializer_list<Variant> &args);
    Variant lrem(const std::initializer_list<Variant> &args);
    Variant ltrim(const std::initializer_list<Variant> &args);
    Variant mget(const std::initializer_list<Variant> &args);
    Variant migrate(const std::initializer_list<Variant> &args);
    Variant move(const std::initializer_list<Variant> &args);
    Variant mset(const std::initializer_list<Variant> &args);
    Variant msetnx(const std::initializer_list<Variant> &args);
    Variant multi(const std::initializer_list<Variant> &args);
    Variant object(const std::initializer_list<Variant> &args);
    Variant open(const std::initializer_list<Variant> &args);
    Variant pconnect(const std::initializer_list<Variant> &args);
    Variant persist(const std::initializer_list<Variant> &args);
    Variant pexpire(const std::initializer_list<Variant> &args);
    Variant pexpireAt(const std::initializer_list<Variant> &args);
    Variant pfadd(const std::initializer_list<Variant> &args);
    Variant pfcount(const std::initializer_list<Variant> &args);
    Variant pfmerge(const std::initializer_list<Variant> &args);
    Variant ping(const std::initializer_list<Variant> &args);
    Variant pipeline();
    Variant popen(const std::initializer_list<Variant> &args);
    Variant psetex(const std::initializer_list<Variant> &args);
    Variant psubscribe(const std::initializer_list<Variant> &args);
    Variant pttl(const std::initializer_list<Variant> &args);
    Variant publish(const std::initializer_list<Variant> &args);
    Variant pubsub(const std::initializer_list<Variant> &args);
    Variant punsubscribe(const std::initializer_list<Variant> &args);
    Variant rPop(const std::initializer_list<Variant> &args);
    Variant randomKey();
    Variant rawcommand(const std::initializer_list<Variant> &args);
    Variant rename(const std::initializer_list<Variant> &args);
    Variant renameNx(const std::initializer_list<Variant> &args);
    Variant reset();
    Variant restore(const std::initializer_list<Variant> &args);
    Variant role();
    Variant rpoplpush(const std::initializer_list<Variant> &args);
    Variant sAdd(const std::initializer_list<Variant> &args);
    Variant sAddArray(const std::initializer_list<Variant> &args);
    Variant sDiff(const std::initializer_list<Variant> &args);
    Variant sDiffStore(const std::initializer_list<Variant> &args);
    Variant sInter(const std::initializer_list<Variant> &args);
    Variant sintercard(const std::initializer_list<Variant> &args);
    Variant sInterStore(const std::initializer_list<Variant> &args);
    Variant sMembers(const std::initializer_list<Variant> &args);
    Variant sMisMember(const std::initializer_list<Variant> &args);
    Variant sMove(const std::initializer_list<Variant> &args);
    Variant sPop(const std::initializer_list<Variant> &args);
    Variant sRandMember(const std::initializer_list<Variant> &args);
    Variant sUnion(const std::initializer_list<Variant> &args);
    Variant sUnionStore(const std::initializer_list<Variant> &args);
    Variant save();
    Variant scan(const std::initializer_list<Variant> &args);
    Variant scard(const std::initializer_list<Variant> &args);
    Variant script(const std::initializer_list<Variant> &args);
    Variant select(const std::initializer_list<Variant> &args);
    Variant set(const std::initializer_list<Variant> &args);
    Variant setBit(const std::initializer_list<Variant> &args);
    Variant setRange(const std::initializer_list<Variant> &args);
    Variant setOption(const std::initializer_list<Variant> &args);
    Variant setex(const std::initializer_list<Variant> &args);
    Variant setnx(const std::initializer_list<Variant> &args);
    Variant sismember(const std::initializer_list<Variant> &args);
    Variant slaveof(const std::initializer_list<Variant> &args);
    Variant replicaof(const std::initializer_list<Variant> &args);
    Variant touch(const std::initializer_list<Variant> &args);
    Variant slowlog(const std::initializer_list<Variant> &args);
    Variant sort(const std::initializer_list<Variant> &args);
    Variant sort_ro(const std::initializer_list<Variant> &args);
    Variant sortAsc(const std::initializer_list<Variant> &args);
    Variant sortAscAlpha(const std::initializer_list<Variant> &args);
    Variant sortDesc(const std::initializer_list<Variant> &args);
    Variant sortDescAlpha(const std::initializer_list<Variant> &args);
    Variant srem(const std::initializer_list<Variant> &args);
    Variant sscan(const std::initializer_list<Variant> &args);
    Variant ssubscribe(const std::initializer_list<Variant> &args);
    Variant strlen(const std::initializer_list<Variant> &args);
    Variant subscribe(const std::initializer_list<Variant> &args);
    Variant sunsubscribe(const std::initializer_list<Variant> &args);
    Variant swapdb(const std::initializer_list<Variant> &args);
    Variant time();
    Variant ttl(const std::initializer_list<Variant> &args);
    Variant type(const std::initializer_list<Variant> &args);
    Variant unlink(const std::initializer_list<Variant> &args);
    Variant unsubscribe(const std::initializer_list<Variant> &args);
    Variant unwatch();
    Variant watch(const std::initializer_list<Variant> &args);
    Variant wait(const std::initializer_list<Variant> &args);
    Variant xack(const std::initializer_list<Variant> &args);
    Variant xadd(const std::initializer_list<Variant> &args);
    Variant xautoclaim(const std::initializer_list<Variant> &args);
    Variant xclaim(const std::initializer_list<Variant> &args);
    Variant xdel(const std::initializer_list<Variant> &args);
    Variant xgroup(const std::initializer_list<Variant> &args);
    Variant xinfo(const std::initializer_list<Variant> &args);
    Variant xlen(const std::initializer_list<Variant> &args);
    Variant xpending(const std::initializer_list<Variant> &args);
    Variant xrange(const std::initializer_list<Variant> &args);
    Variant xread(const std::initializer_list<Variant> &args);
    Variant xreadgroup(const std::initializer_list<Variant> &args);
    Variant xrevrange(const std::initializer_list<Variant> &args);
    Variant xtrim(const std::initializer_list<Variant> &args);
    Variant zAdd(const std::initializer_list<Variant> &args);
    Variant zCard(const std::initializer_list<Variant> &args);
    Variant zCount(const std::initializer_list<Variant> &args);
    Variant zIncrBy(const std::initializer_list<Variant> &args);
    Variant zLexCount(const std::initializer_list<Variant> &args);
    Variant zMscore(const std::initializer_list<Variant> &args);
    Variant zPopMax(const std::initializer_list<Variant> &args);
    Variant zPopMin(const std::initializer_list<Variant> &args);
    Variant zRange(const std::initializer_list<Variant> &args);
    Variant zRangeByLex(const std::initializer_list<Variant> &args);
    Variant zRangeByScore(const std::initializer_list<Variant> &args);
    Variant zrangestore(const std::initializer_list<Variant> &args);
    Variant zRandMember(const std::initializer_list<Variant> &args);
    Variant zRank(const std::initializer_list<Variant> &args);
    Variant zRem(const std::initializer_list<Variant> &args);
    Variant zRemRangeByLex(const std::initializer_list<Variant> &args);
    Variant zRemRangeByRank(const std::initializer_list<Variant> &args);
    Variant zRemRangeByScore(const std::initializer_list<Variant> &args);
    Variant zRevRange(const std::initializer_list<Variant> &args);
    Variant zRevRangeByLex(const std::initializer_list<Variant> &args);
    Variant zRevRangeByScore(const std::initializer_list<Variant> &args);
    Variant zRevRank(const std::initializer_list<Variant> &args);
    Variant zScore(const std::initializer_list<Variant> &args);
    Variant zdiff(const std::initializer_list<Variant> &args);
    Variant zdiffstore(const std::initializer_list<Variant> &args);
    Variant zinter(const std::initializer_list<Variant> &args);
    Variant zintercard(const std::initializer_list<Variant> &args);
    Variant zinterstore(const std::initializer_list<Variant> &args);
    Variant zscan(const std::initializer_list<Variant> &args);
    Variant zunion(const std::initializer_list<Variant> &args);
    Variant zunionstore(const std::initializer_list<Variant> &args);
};

class RedisArray {
  private:
    Variant _this;
  public:
    Variant __call(const std::initializer_list<Variant> &args);
    RedisArray(const std::initializer_list<Variant> &args);
    Variant _continuum();
    Variant _distributor();
    Variant _function();
    Variant _hosts();
    Variant _instance(const std::initializer_list<Variant> &args);
    Variant _rehash(const std::initializer_list<Variant> &args);
    Variant _target(const std::initializer_list<Variant> &args);
    Variant bgsave();
    Variant del(const std::initializer_list<Variant> &args);
    Variant discard();
    Variant exec();
    Variant flushall();
    Variant flushdb();
    Variant getOption(const std::initializer_list<Variant> &args);
    Variant hscan(const std::initializer_list<Variant> &args);
    Variant info();
    Variant keys(const std::initializer_list<Variant> &args);
    Variant mget(const std::initializer_list<Variant> &args);
    Variant mset(const std::initializer_list<Variant> &args);
    Variant multi(const std::initializer_list<Variant> &args);
    Variant ping();
    Variant save();
    Variant scan(const std::initializer_list<Variant> &args);
    Variant select(const std::initializer_list<Variant> &args);
    Variant setOption(const std::initializer_list<Variant> &args);
    Variant sscan(const std::initializer_list<Variant> &args);
    Variant unlink(const std::initializer_list<Variant> &args);
    Variant unwatch();
    Variant zscan(const std::initializer_list<Variant> &args);
};

class RedisCluster {
  private:
    Variant _this;
  public:
    RedisCluster(const std::initializer_list<Variant> &args);
    Variant _compress(const std::initializer_list<Variant> &args);
    Variant _uncompress(const std::initializer_list<Variant> &args);
    Variant _serialize(const std::initializer_list<Variant> &args);
    Variant _unserialize(const std::initializer_list<Variant> &args);
    Variant _pack(const std::initializer_list<Variant> &args);
    Variant _unpack(const std::initializer_list<Variant> &args);
    Variant _prefix(const std::initializer_list<Variant> &args);
    Variant _masters();
    Variant _redir();
    Variant acl(const std::initializer_list<Variant> &args);
    Variant append(const std::initializer_list<Variant> &args);
    Variant bgrewriteaof(const std::initializer_list<Variant> &args);
    Variant bgsave(const std::initializer_list<Variant> &args);
    Variant bitcount(const std::initializer_list<Variant> &args);
    Variant bitop(const std::initializer_list<Variant> &args);
    Variant bitpos(const std::initializer_list<Variant> &args);
    Variant blpop(const std::initializer_list<Variant> &args);
    Variant brpop(const std::initializer_list<Variant> &args);
    Variant brpoplpush(const std::initializer_list<Variant> &args);
    Variant lmove(const std::initializer_list<Variant> &args);
    Variant blmove(const std::initializer_list<Variant> &args);
    Variant bzpopmax(const std::initializer_list<Variant> &args);
    Variant bzpopmin(const std::initializer_list<Variant> &args);
    Variant bzmpop(const std::initializer_list<Variant> &args);
    Variant zmpop(const std::initializer_list<Variant> &args);
    Variant blmpop(const std::initializer_list<Variant> &args);
    Variant lmpop(const std::initializer_list<Variant> &args);
    Variant clearlasterror();
    Variant client(const std::initializer_list<Variant> &args);
    Variant close();
    Variant cluster(const std::initializer_list<Variant> &args);
    Variant command(const std::initializer_list<Variant> &args);
    Variant config(const std::initializer_list<Variant> &args);
    Variant dbsize(const std::initializer_list<Variant> &args);
    Variant copy(const std::initializer_list<Variant> &args);
    Variant decr(const std::initializer_list<Variant> &args);
    Variant decrby(const std::initializer_list<Variant> &args);
    Variant decrbyfloat(const std::initializer_list<Variant> &args);
    Variant del(const std::initializer_list<Variant> &args);
    Variant discard();
    Variant dump(const std::initializer_list<Variant> &args);
    Variant echo(const std::initializer_list<Variant> &args);
    Variant eval(const std::initializer_list<Variant> &args);
    Variant eval_ro(const std::initializer_list<Variant> &args);
    Variant evalsha(const std::initializer_list<Variant> &args);
    Variant evalsha_ro(const std::initializer_list<Variant> &args);
    Variant exec();
    Variant exists(const std::initializer_list<Variant> &args);
    Variant touch(const std::initializer_list<Variant> &args);
    Variant expire(const std::initializer_list<Variant> &args);
    Variant expireat(const std::initializer_list<Variant> &args);
    Variant expiretime(const std::initializer_list<Variant> &args);
    Variant pexpiretime(const std::initializer_list<Variant> &args);
    Variant flushall(const std::initializer_list<Variant> &args);
    Variant flushdb(const std::initializer_list<Variant> &args);
    Variant geoadd(const std::initializer_list<Variant> &args);
    Variant geodist(const std::initializer_list<Variant> &args);
    Variant geohash(const std::initializer_list<Variant> &args);
    Variant geopos(const std::initializer_list<Variant> &args);
    Variant georadius(const std::initializer_list<Variant> &args);
    Variant georadius_ro(const std::initializer_list<Variant> &args);
    Variant georadiusbymember(const std::initializer_list<Variant> &args);
    Variant georadiusbymember_ro(const std::initializer_list<Variant> &args);
    Variant geosearch(const std::initializer_list<Variant> &args);
    Variant geosearchstore(const std::initializer_list<Variant> &args);
    Variant get(const std::initializer_list<Variant> &args);
    Variant getbit(const std::initializer_list<Variant> &args);
    Variant getlasterror();
    Variant getmode();
    Variant getoption(const std::initializer_list<Variant> &args);
    Variant getrange(const std::initializer_list<Variant> &args);
    Variant lcs(const std::initializer_list<Variant> &args);
    Variant getset(const std::initializer_list<Variant> &args);
    Variant gettransferredbytes();
    Variant cleartransferredbytes();
    Variant hdel(const std::initializer_list<Variant> &args);
    Variant hexists(const std::initializer_list<Variant> &args);
    Variant hget(const std::initializer_list<Variant> &args);
    Variant hgetall(const std::initializer_list<Variant> &args);
    Variant hincrby(const std::initializer_list<Variant> &args);
    Variant hincrbyfloat(const std::initializer_list<Variant> &args);
    Variant hkeys(const std::initializer_list<Variant> &args);
    Variant hlen(const std::initializer_list<Variant> &args);
    Variant hmget(const std::initializer_list<Variant> &args);
    Variant hmset(const std::initializer_list<Variant> &args);
    Variant hscan(const std::initializer_list<Variant> &args);
    Variant hrandfield(const std::initializer_list<Variant> &args);
    Variant hset(const std::initializer_list<Variant> &args);
    Variant hsetnx(const std::initializer_list<Variant> &args);
    Variant hstrlen(const std::initializer_list<Variant> &args);
    Variant hvals(const std::initializer_list<Variant> &args);
    Variant incr(const std::initializer_list<Variant> &args);
    Variant incrby(const std::initializer_list<Variant> &args);
    Variant incrbyfloat(const std::initializer_list<Variant> &args);
    Variant info(const std::initializer_list<Variant> &args);
    Variant keys(const std::initializer_list<Variant> &args);
    Variant lastsave(const std::initializer_list<Variant> &args);
    Variant lget(const std::initializer_list<Variant> &args);
    Variant lindex(const std::initializer_list<Variant> &args);
    Variant linsert(const std::initializer_list<Variant> &args);
    Variant llen(const std::initializer_list<Variant> &args);
    Variant lpop(const std::initializer_list<Variant> &args);
    Variant lpos(const std::initializer_list<Variant> &args);
    Variant lpush(const std::initializer_list<Variant> &args);
    Variant lpushx(const std::initializer_list<Variant> &args);
    Variant lrange(const std::initializer_list<Variant> &args);
    Variant lrem(const std::initializer_list<Variant> &args);
    Variant lset(const std::initializer_list<Variant> &args);
    Variant ltrim(const std::initializer_list<Variant> &args);
    Variant mget(const std::initializer_list<Variant> &args);
    Variant mset(const std::initializer_list<Variant> &args);
    Variant msetnx(const std::initializer_list<Variant> &args);
    Variant multi(const std::initializer_list<Variant> &args);
    Variant object(const std::initializer_list<Variant> &args);
    Variant persist(const std::initializer_list<Variant> &args);
    Variant pexpire(const std::initializer_list<Variant> &args);
    Variant pexpireat(const std::initializer_list<Variant> &args);
    Variant pfadd(const std::initializer_list<Variant> &args);
    Variant pfcount(const std::initializer_list<Variant> &args);
    Variant pfmerge(const std::initializer_list<Variant> &args);
    Variant ping(const std::initializer_list<Variant> &args);
    Variant psetex(const std::initializer_list<Variant> &args);
    Variant psubscribe(const std::initializer_list<Variant> &args);
    Variant pttl(const std::initializer_list<Variant> &args);
    Variant publish(const std::initializer_list<Variant> &args);
    Variant pubsub(const std::initializer_list<Variant> &args);
    Variant punsubscribe(const std::initializer_list<Variant> &args);
    Variant randomkey(const std::initializer_list<Variant> &args);
    Variant rawcommand(const std::initializer_list<Variant> &args);
    Variant rename(const std::initializer_list<Variant> &args);
    Variant renamenx(const std::initializer_list<Variant> &args);
    Variant restore(const std::initializer_list<Variant> &args);
    Variant role(const std::initializer_list<Variant> &args);
    Variant rpop(const std::initializer_list<Variant> &args);
    Variant rpoplpush(const std::initializer_list<Variant> &args);
    Variant rpush(const std::initializer_list<Variant> &args);
    Variant rpushx(const std::initializer_list<Variant> &args);
    Variant sadd(const std::initializer_list<Variant> &args);
    Variant saddarray(const std::initializer_list<Variant> &args);
    Variant save(const std::initializer_list<Variant> &args);
    Variant scan(const std::initializer_list<Variant> &args);
    Variant scard(const std::initializer_list<Variant> &args);
    Variant script(const std::initializer_list<Variant> &args);
    Variant sdiff(const std::initializer_list<Variant> &args);
    Variant sdiffstore(const std::initializer_list<Variant> &args);
    Variant set(const std::initializer_list<Variant> &args);
    Variant _setbit(const std::initializer_list<Variant> &args);
    Variant setex(const std::initializer_list<Variant> &args);
    Variant setnx(const std::initializer_list<Variant> &args);
    Variant setoption(const std::initializer_list<Variant> &args);
    Variant setrange(const std::initializer_list<Variant> &args);
    Variant sinter(const std::initializer_list<Variant> &args);
    Variant sintercard(const std::initializer_list<Variant> &args);
    Variant sinterstore(const std::initializer_list<Variant> &args);
    Variant sismember(const std::initializer_list<Variant> &args);
    Variant smismember(const std::initializer_list<Variant> &args);
    Variant slowlog(const std::initializer_list<Variant> &args);
    Variant smembers(const std::initializer_list<Variant> &args);
    Variant smove(const std::initializer_list<Variant> &args);
    Variant sort(const std::initializer_list<Variant> &args);
    Variant sort_ro(const std::initializer_list<Variant> &args);
    Variant spop(const std::initializer_list<Variant> &args);
    Variant srandmember(const std::initializer_list<Variant> &args);
    Variant srem(const std::initializer_list<Variant> &args);
    Variant sscan(const std::initializer_list<Variant> &args);
    Variant strlen(const std::initializer_list<Variant> &args);
    Variant subscribe(const std::initializer_list<Variant> &args);
    Variant sunion(const std::initializer_list<Variant> &args);
    Variant sunionstore(const std::initializer_list<Variant> &args);
    Variant time(const std::initializer_list<Variant> &args);
    Variant ttl(const std::initializer_list<Variant> &args);
    Variant type(const std::initializer_list<Variant> &args);
    Variant unsubscribe(const std::initializer_list<Variant> &args);
    Variant unlink(const std::initializer_list<Variant> &args);
    Variant unwatch();
    Variant watch(const std::initializer_list<Variant> &args);
    Variant xack(const std::initializer_list<Variant> &args);
    Variant xadd(const std::initializer_list<Variant> &args);
    Variant xclaim(const std::initializer_list<Variant> &args);
    Variant xdel(const std::initializer_list<Variant> &args);
    Variant xgroup(const std::initializer_list<Variant> &args);
    Variant xautoclaim(const std::initializer_list<Variant> &args);
    Variant xinfo(const std::initializer_list<Variant> &args);
    Variant xlen(const std::initializer_list<Variant> &args);
    Variant xpending(const std::initializer_list<Variant> &args);
    Variant xrange(const std::initializer_list<Variant> &args);
    Variant xread(const std::initializer_list<Variant> &args);
    Variant xreadgroup(const std::initializer_list<Variant> &args);
    Variant xrevrange(const std::initializer_list<Variant> &args);
    Variant xtrim(const std::initializer_list<Variant> &args);
    Variant zadd(const std::initializer_list<Variant> &args);
    Variant zcard(const std::initializer_list<Variant> &args);
    Variant zcount(const std::initializer_list<Variant> &args);
    Variant zincrby(const std::initializer_list<Variant> &args);
    Variant zinterstore(const std::initializer_list<Variant> &args);
    Variant zintercard(const std::initializer_list<Variant> &args);
    Variant zlexcount(const std::initializer_list<Variant> &args);
    Variant zpopmax(const std::initializer_list<Variant> &args);
    Variant zpopmin(const std::initializer_list<Variant> &args);
    Variant zrange(const std::initializer_list<Variant> &args);
    Variant zrangestore(const std::initializer_list<Variant> &args);
    Variant zrandmember(const std::initializer_list<Variant> &args);
    Variant zrangebylex(const std::initializer_list<Variant> &args);
    Variant zrangebyscore(const std::initializer_list<Variant> &args);
    Variant zrank(const std::initializer_list<Variant> &args);
    Variant zrem(const std::initializer_list<Variant> &args);
    Variant zremrangebylex(const std::initializer_list<Variant> &args);
    Variant zremrangebyrank(const std::initializer_list<Variant> &args);
    Variant zremrangebyscore(const std::initializer_list<Variant> &args);
    Variant zrevrange(const std::initializer_list<Variant> &args);
    Variant zrevrangebylex(const std::initializer_list<Variant> &args);
    Variant zrevrangebyscore(const std::initializer_list<Variant> &args);
    Variant zrevrank(const std::initializer_list<Variant> &args);
    Variant zscan(const std::initializer_list<Variant> &args);
    Variant zscore(const std::initializer_list<Variant> &args);
    Variant zmscore(const std::initializer_list<Variant> &args);
    Variant zunionstore(const std::initializer_list<Variant> &args);
    Variant zinter(const std::initializer_list<Variant> &args);
    Variant zdiffstore(const std::initializer_list<Variant> &args);
    Variant zunion(const std::initializer_list<Variant> &args);
    Variant zdiff(const std::initializer_list<Variant> &args);
};

class RedisClusterException {
  private:
    Variant _this;
  public:
    RedisClusterException(const std::initializer_list<Variant> &args);
    Variant __wakeup();
    Variant getMessage();
    Variant getCode();
    Variant getFile();
    Variant getLine();
    Variant getTrace();
    Variant getPrevious();
    Variant getTraceAsString();
    Variant __toString();
};

class RedisSentinel {
  private:
    Variant _this;
  public:
    RedisSentinel(const std::initializer_list<Variant> &args);
    Variant ckquorum(const std::initializer_list<Variant> &args);
    Variant failover(const std::initializer_list<Variant> &args);
    Variant flushconfig();
    Variant getMasterAddrByName(const std::initializer_list<Variant> &args);
    Variant master(const std::initializer_list<Variant> &args);
    Variant masters();
    Variant myid();
    Variant ping();
    Variant reset(const std::initializer_list<Variant> &args);
    Variant sentinels(const std::initializer_list<Variant> &args);
    Variant slaves(const std::initializer_list<Variant> &args);
};

class RedisException {
  private:
    Variant _this;
  public:
    RedisException(const std::initializer_list<Variant> &args);
    Variant __wakeup();
    Variant getMessage();
    Variant getCode();
    Variant getFile();
    Variant getLine();
    Variant getTrace();
    Variant getPrevious();
    Variant getTraceAsString();
    Variant __toString();
};

}
