clang-format -i src/core/*.cc
clang-format -i src/class/*.cc
clang-format -i src/func/*.cc
clang-format -i src/const/*.cc
clang-format -i src/misc/*.cc
clang-format -i src/std/*.cc
clang-format -i src/misc/typephp_helper.h
clang-format -i src/misc/typephp_fiber_generator.h
clang-format -i include/*.h
clang-format -i tests/src/*.cpp
