clang-format -i src/core/*.cc
clang-format -i src/class/*.cc
clang-format -i src/func/*.cc
clang-format -i src/const/*.cc
clang-format -i src/misc/*.cc
clang-format -i src/misc/php_std_*.cpp
clang-format -i src/misc/php_std_*.h
clang-format -i src/misc/php_aot_helper.h
clang-format -i include/*.h
clang-format -i tests/src/*.cpp
