#include "phpx.h"

namespace php {
Variant CAL_GREGORIAN{0};
Variant CAL_JULIAN{1};
Variant CAL_JEWISH{2};
Variant CAL_FRENCH{3};
Variant CAL_NUM_CALS{4};
Variant CAL_DOW_DAYNO{0};
Variant CAL_DOW_SHORT{2};
Variant CAL_DOW_LONG{1};
Variant CAL_MONTH_GREGORIAN_SHORT{0};
Variant CAL_MONTH_GREGORIAN_LONG{1};
Variant CAL_MONTH_JULIAN_SHORT{2};
Variant CAL_MONTH_JULIAN_LONG{3};
Variant CAL_MONTH_JEWISH{4};
Variant CAL_MONTH_FRENCH{5};
Variant CAL_EASTER_DEFAULT{0};
Variant CAL_EASTER_ROMAN{1};
Variant CAL_EASTER_ALWAYS_GREGORIAN{2};
Variant CAL_EASTER_ALWAYS_JULIAN{3};
Variant CAL_JEWISH_ADD_ALAFIM_GERESH{2};
Variant CAL_JEWISH_ADD_ALAFIM{4};
Variant CAL_JEWISH_ADD_GERESHAYIM{8};
}  // namespace php
