#include "phpx.h"

namespace php {
Variant E_ERROR_{1};
Variant E_WARNING_{2};
Variant E_PARSE_{4};
Variant E_NOTICE_{8};
Variant E_CORE_ERROR_{16};
Variant E_CORE_WARNING_{32};
Variant E_COMPILE_ERROR_{64};
Variant E_COMPILE_WARNING_{128};
Variant E_USER_ERROR_{256};
Variant E_USER_WARNING_{512};
Variant E_USER_NOTICE_{1024};
Variant E_STRICT_{2048};
Variant E_RECOVERABLE_ERROR_{4096};
Variant E_DEPRECATED_{8192};
Variant E_USER_DEPRECATED_{16384};
Variant E_ALL_{30719};
Variant DEBUG_BACKTRACE_PROVIDE_OBJECT_{1};
Variant DEBUG_BACKTRACE_IGNORE_ARGS_{2};
Variant ZEND_THREAD_SAFE_{true};
Variant ZEND_DEBUG_BUILD_{true};
Variant TRUE_{true};
Variant FALSE_{false};
Variant NULL_{nullptr};
Variant PHP_VERSION_{ZEND_STRL("8.4.14"), true};
Variant PHP_MAJOR_VERSION_{8};
Variant PHP_MINOR_VERSION_{4};
Variant PHP_RELEASE_VERSION_{14};
Variant PHP_EXTRA_VERSION_{ZEND_STRL(""), true};
Variant PHP_VERSION_ID_{80414};
Variant PHP_ZTS_{true};
Variant PHP_DEBUG_{true};
Variant PHP_OS_{ZEND_STRL("Linux"), true};
Variant PHP_OS_FAMILY_{ZEND_STRL("Linux"), true};
Variant DEFAULT_INCLUDE_PATH_{ZEND_STRL(".:/opt/php-8.4/lib/php"), true};
Variant PEAR_INSTALL_DIR_{ZEND_STRL("/opt/php-8.4/lib/php"), true};
Variant PEAR_EXTENSION_DIR_{ZEND_STRL("/opt/php-8.4/lib/php/extensions/debug-zts-20240924"), true};
Variant PHP_EXTENSION_DIR_{ZEND_STRL("/opt/php-8.4/lib/php/extensions/debug-zts-20240924"), true};
Variant PHP_PREFIX_{ZEND_STRL("/opt/php-8.4"), true};
Variant PHP_BINDIR_{ZEND_STRL("/opt/php-8.4/bin"), true};
Variant PHP_SBINDIR_{ZEND_STRL("/opt/php-8.4/sbin"), true};
Variant PHP_MANDIR_{ZEND_STRL("/opt/php-8.4/php/man"), true};
Variant PHP_LIBDIR_{ZEND_STRL("/opt/php-8.4/lib/php"), true};
Variant PHP_DATADIR_{ZEND_STRL("/opt/php-8.4/share/php"), true};
Variant PHP_SYSCONFDIR_{ZEND_STRL("/opt/php-8.4/etc"), true};
Variant PHP_LOCALSTATEDIR_{ZEND_STRL("/opt/php-8.4/var"), true};
Variant PHP_CONFIG_FILE_PATH_{ZEND_STRL("/opt/php-8.4/lib"), true};
Variant PHP_CONFIG_FILE_SCAN_DIR_{ZEND_STRL(""), true};
Variant PHP_SHLIB_SUFFIX_{ZEND_STRL("so"), true};
Variant PHP_EOL_{ZEND_STRL("\n"), true};
Variant PHP_MAXPATHLEN_{4096};
Variant PHP_INT_MAX_{LONG_MAX};
Variant PHP_INT_MIN_{LONG_MIN};
Variant PHP_INT_SIZE_{8};
Variant PHP_FD_SETSIZE_{1024};
Variant PHP_FLOAT_DIG_{15};
Variant PHP_FLOAT_EPSILON_{2.2204460492503131E-16};
Variant PHP_FLOAT_MAX_{1.7976931348623157E+308};
Variant PHP_FLOAT_MIN_{2.2250738585072014E-308};
Variant PHP_OUTPUT_HANDLER_START_{1};
Variant PHP_OUTPUT_HANDLER_WRITE_{0};
Variant PHP_OUTPUT_HANDLER_FLUSH_{4};
Variant PHP_OUTPUT_HANDLER_CLEAN_{2};
Variant PHP_OUTPUT_HANDLER_FINAL_{8};
Variant PHP_OUTPUT_HANDLER_CONT_{0};
Variant PHP_OUTPUT_HANDLER_END_{8};
Variant PHP_OUTPUT_HANDLER_CLEANABLE_{16};
Variant PHP_OUTPUT_HANDLER_FLUSHABLE_{32};
Variant PHP_OUTPUT_HANDLER_REMOVABLE_{64};
Variant PHP_OUTPUT_HANDLER_STDFLAGS_{112};
Variant PHP_OUTPUT_HANDLER_STARTED_{4096};
Variant PHP_OUTPUT_HANDLER_DISABLED_{8192};
Variant PHP_OUTPUT_HANDLER_PROCESSED_{16384};
Variant UPLOAD_ERR_OK_{0};
Variant UPLOAD_ERR_INI_SIZE_{1};
Variant UPLOAD_ERR_FORM_SIZE_{2};
Variant UPLOAD_ERR_PARTIAL_{3};
Variant UPLOAD_ERR_NO_FILE_{4};
Variant UPLOAD_ERR_NO_TMP_DIR_{6};
Variant UPLOAD_ERR_CANT_WRITE_{7};
Variant UPLOAD_ERR_EXTENSION_{8};
Variant PHP_SAPI_{ZEND_STRL("cli"), true};
Variant PHP_BINARY_{ZEND_STRL("/opt/php-8.4/bin/php"), true};
Variant PHP_CLI_PROCESS_TITLE_{true};
}  // namespace php
