#include "phpx.h"

namespace php {
Variant JSON_HEX_TAG { 1 };
Variant JSON_HEX_AMP { 2 };
Variant JSON_HEX_APOS { 4 };
Variant JSON_HEX_QUOT { 8 };
Variant JSON_FORCE_OBJECT { 16 };
Variant JSON_NUMERIC_CHECK { 32 };
Variant JSON_UNESCAPED_SLASHES { 64 };
Variant JSON_PRETTY_PRINT { 128 };
Variant JSON_UNESCAPED_UNICODE { 256 };
Variant JSON_PARTIAL_OUTPUT_ON_ERROR { 512 };
Variant JSON_PRESERVE_ZERO_FRACTION { 1024 };
Variant JSON_UNESCAPED_LINE_TERMINATORS { 2048 };
Variant JSON_OBJECT_AS_ARRAY { 1 };
Variant JSON_BIGINT_AS_STRING { 2 };
Variant JSON_INVALID_UTF8_IGNORE { 1048576 };
Variant JSON_INVALID_UTF8_SUBSTITUTE { 2097152 };
Variant JSON_THROW_ON_ERROR { 4194304 };
Variant JSON_ERROR_NONE { 0 };
Variant JSON_ERROR_DEPTH { 1 };
Variant JSON_ERROR_STATE_MISMATCH { 2 };
Variant JSON_ERROR_CTRL_CHAR { 3 };
Variant JSON_ERROR_SYNTAX { 4 };
Variant JSON_ERROR_UTF8 { 5 };
Variant JSON_ERROR_RECURSION { 6 };
Variant JSON_ERROR_INF_OR_NAN { 7 };
Variant JSON_ERROR_UNSUPPORTED_TYPE { 8 };
Variant JSON_ERROR_INVALID_PROPERTY_NAME { 9 };
Variant JSON_ERROR_UTF16 { 10 };
Variant JSON_ERROR_NON_BACKED_ENUM { 11 };
}
