#include "phpx.h"

namespace php {
Variant XML_ERROR_NONE { 0 };
Variant XML_ERROR_NO_MEMORY { 1 };
Variant XML_ERROR_SYNTAX { 2 };
Variant XML_ERROR_NO_ELEMENTS { 3 };
Variant XML_ERROR_INVALID_TOKEN { 4 };
Variant XML_ERROR_UNCLOSED_TOKEN { 5 };
Variant XML_ERROR_PARTIAL_CHAR { 6 };
Variant XML_ERROR_TAG_MISMATCH { 7 };
Variant XML_ERROR_DUPLICATE_ATTRIBUTE { 8 };
Variant XML_ERROR_JUNK_AFTER_DOC_ELEMENT { 9 };
Variant XML_ERROR_PARAM_ENTITY_REF { 10 };
Variant XML_ERROR_UNDEFINED_ENTITY { 11 };
Variant XML_ERROR_RECURSIVE_ENTITY_REF { 12 };
Variant XML_ERROR_ASYNC_ENTITY { 13 };
Variant XML_ERROR_BAD_CHAR_REF { 14 };
Variant XML_ERROR_BINARY_ENTITY_REF { 15 };
Variant XML_ERROR_ATTRIBUTE_EXTERNAL_ENTITY_REF { 16 };
Variant XML_ERROR_MISPLACED_XML_PI { 17 };
Variant XML_ERROR_UNKNOWN_ENCODING { 18 };
Variant XML_ERROR_INCORRECT_ENCODING { 19 };
Variant XML_ERROR_UNCLOSED_CDATA_SECTION { 20 };
Variant XML_ERROR_EXTERNAL_ENTITY_HANDLING { 21 };
Variant XML_OPTION_CASE_FOLDING { 1 };
Variant XML_OPTION_TARGET_ENCODING { 2 };
Variant XML_OPTION_SKIP_TAGSTART { 3 };
Variant XML_OPTION_SKIP_WHITE { 4 };
Variant XML_SAX_IMPL { ZEND_STRL("libxml"), true };
}
