namespace php {
Variant die(const Variant &status = 0);
Variant zend_version();
Variant func_num_args();
Variant func_get_arg(const Variant &position);
Variant func_get_args();
Variant strcmp(const Variant &string1, const Variant &string2);
Variant strncmp(const Variant &string1, const Variant &string2, const Variant &length);
Variant strcasecmp(const Variant &string1, const Variant &string2);
Variant strncasecmp(const Variant &string1, const Variant &string2, const Variant &length);
Variant error_reporting(const Variant &error_level = {});
Variant define(const Variant &constant_name, const Variant &value, const Variant &case_insensitive = false);
Variant defined(const Variant &constant_name);
Variant get_class(const Variant &object = {});
Variant get_called_class();
Variant get_parent_class(const Variant &object_or_class = {});
Variant is_subclass_of(const Variant &object_or_class, const Variant &_class, const Variant &allow_string = true);
Variant is_a(const Variant &object_or_class, const Variant &_class, const Variant &allow_string = false);
Variant get_class_vars(const Variant &_class);
Variant get_object_vars(const Variant &object);
Variant get_mangled_object_vars(const Variant &object);
Variant get_class_methods(const Variant &object_or_class);
Variant method_exists(const Variant &object_or_class, const Variant &method);
Variant property_exists(const Variant &object_or_class, const Variant &property);
Variant class_exists(const Variant &_class, const Variant &autoload = true);
Variant interface_exists(const Variant &interface, const Variant &autoload = true);
Variant trait_exists(const Variant &trait, const Variant &autoload = true);
Variant enum_exists(const Variant &_enum, const Variant &autoload = true);
Variant function_exists(const Variant &function);
Variant class_alias(const Variant &_class, const Variant &alias, const Variant &autoload = true);
Variant get_included_files();
Variant get_required_files();
Variant trigger_error(const Variant &message, const Variant &error_level = 1024);
Variant user_error(const Variant &message, const Variant &error_level = 1024);
Variant set_error_handler(const Variant &callback, const Variant &error_levels = 30719);
Variant restore_error_handler();
Variant set_exception_handler(const Variant &callback);
Variant restore_exception_handler();
Variant get_declared_classes();
Variant get_declared_traits();
Variant get_declared_interfaces();
Variant get_defined_functions(const Variant &exclude_disabled = true);
Variant get_defined_vars();
Variant get_resource_type(const Variant &resource);
Variant get_resource_id(const Variant &resource);
Variant get_resources(const Variant &type = {});
Variant get_loaded_extensions(const Variant &zend_extensions = false);
Variant get_defined_constants(const Variant &categorize = false);
Variant debug_backtrace(const Variant &options = 1, const Variant &limit = 0);
Variant debug_print_backtrace(const Variant &options = 0, const Variant &limit = 0);
Variant extension_loaded(const Variant &extension);
Variant get_extension_funcs(const Variant &extension);
Variant zend_thread_id();
Variant gc_mem_caches();
Variant gc_collect_cycles();
Variant gc_enabled();
Variant gc_enable();
Variant gc_disable();
Variant gc_status();
}
