namespace php {
extern Variant pcntl_fork;
extern Variant pcntl_waitpid;
extern Variant pcntl_wait;
extern Variant pcntl_signal;
extern Variant pcntl_signal_get_handler;
extern Variant pcntl_signal_dispatch;
extern Variant pcntl_sigprocmask;
extern Variant pcntl_sigwaitinfo;
extern Variant pcntl_sigtimedwait;
extern Variant pcntl_wifexited;
extern Variant pcntl_wifstopped;
extern Variant pcntl_wifcontinued;
extern Variant pcntl_wifsignaled;
extern Variant pcntl_wexitstatus;
extern Variant pcntl_wtermsig;
extern Variant pcntl_wstopsig;
extern Variant pcntl_exec;
extern Variant pcntl_alarm;
extern Variant pcntl_get_last_error;
extern Variant pcntl_errno;
extern Variant pcntl_getpriority;
extern Variant pcntl_setpriority;
extern Variant pcntl_strerror;
extern Variant pcntl_async_signals;
extern Variant pcntl_unshare;
}
