namespace php {
Variant pcntl_fork();
Variant pcntl_waitpid(const Variant &process_id, const Reference &status, const Variant &flags = 0, const Reference &resource_usage = getEmptyArrayRef());
Variant pcntl_waitid(const Variant &idtype = 0, const Variant &id = {}, const Reference &info = getEmptyArrayRef(), const Variant &flags = 4);
Variant pcntl_wait(const Reference &status, const Variant &flags = 0, const Reference &resource_usage = getEmptyArrayRef());
Variant pcntl_signal(const Variant &signal, const Variant &handler, const Variant &restart_syscalls = true);
Variant pcntl_signal_get_handler(const Variant &signal);
Variant pcntl_signal_dispatch();
Variant pcntl_sigprocmask(const Variant &mode, const Variant &signals, const Reference &old_signals = {});
Variant pcntl_sigwaitinfo(const Variant &signals, const Reference &info = getEmptyArrayRef());
Variant pcntl_sigtimedwait(const Variant &signals, const Reference &info = getEmptyArrayRef(), const Variant &seconds = 0, const Variant &nanoseconds = 0);
Variant pcntl_wifexited(const Variant &status);
Variant pcntl_wifstopped(const Variant &status);
Variant pcntl_wifcontinued(const Variant &status);
Variant pcntl_wifsignaled(const Variant &status);
Variant pcntl_wexitstatus(const Variant &status);
Variant pcntl_wtermsig(const Variant &status);
Variant pcntl_wstopsig(const Variant &status);
Variant pcntl_exec(const Variant &path, const Variant &args = Array{}, const Variant &env_vars = Array{});
Variant pcntl_alarm(const Variant &seconds);
Variant pcntl_get_last_error();
Variant pcntl_errno();
Variant pcntl_getpriority(const Variant &process_id = {}, const Variant &mode = 0);
Variant pcntl_setpriority(const Variant &priority, const Variant &process_id = {}, const Variant &mode = 0);
Variant pcntl_strerror(const Variant &error_code);
Variant pcntl_async_signals(const Variant &enable = {});
Variant pcntl_unshare(const Variant &flags);
Variant pcntl_getcpuaffinity(const Variant &process_id = {});
Variant pcntl_setcpuaffinity(const Variant &process_id = {}, const Variant &cpu_ids = Array{});
Variant pcntl_getcpu();
}
