namespace php {
extern Variant session_name;
extern Variant session_module_name;
extern Variant session_save_path;
extern Variant session_id;
extern Variant session_create_id;
extern Variant session_regenerate_id;
extern Variant session_decode;
extern Variant session_encode;
extern Variant session_destroy;
extern Variant session_unset;
extern Variant session_gc;
extern Variant session_get_cookie_params;
extern Variant session_write_close;
extern Variant session_abort;
extern Variant session_reset;
extern Variant session_status;
extern Variant session_register_shutdown;
extern Variant session_commit;
extern Variant session_set_save_handler;
extern Variant session_cache_limiter;
extern Variant session_cache_expire;
extern Variant session_set_cookie_params;
extern Variant session_start;
}
