namespace php {
Variant ob_gzhandler(const Variant &data, const Variant &flags);
Variant zlib_get_coding_type();
Variant gzfile(const Variant &filename, const Variant &use_include_path = 0);
Variant gzopen(const Variant &filename, const Variant &mode, const Variant &use_include_path = 0);
Variant readgzfile(const Variant &filename, const Variant &use_include_path = 0);
Variant zlib_encode(const Variant &data, const Variant &encoding, const Variant &level = -1);
Variant zlib_decode(const Variant &data, const Variant &max_length = 0);
Variant gzdeflate(const Variant &data, const Variant &level = -1, const Variant &encoding = -15);
Variant gzencode(const Variant &data, const Variant &level = -1, const Variant &encoding = 31);
Variant gzcompress(const Variant &data, const Variant &level = -1, const Variant &encoding = 15);
Variant gzinflate(const Variant &data, const Variant &max_length = 0);
Variant gzdecode(const Variant &data, const Variant &max_length = 0);
Variant gzuncompress(const Variant &data, const Variant &max_length = 0);
Variant gzwrite(const Variant &stream, const Variant &data, const Variant &length = {});
Variant gzputs(const Variant &stream, const Variant &data, const Variant &length = {});
Variant gzrewind(const Variant &stream);
Variant gzclose(const Variant &stream);
Variant gzeof(const Variant &stream);
Variant gzgetc(const Variant &stream);
Variant gzpassthru(const Variant &stream);
Variant gzseek(const Variant &stream, const Variant &offset, const Variant &whence = 0);
Variant gztell(const Variant &stream);
Variant gzread(const Variant &stream, const Variant &length);
Variant gzgets(const Variant &stream, const Variant &length = {});
Variant deflate_init(const Variant &encoding, const Variant &options = Array{});
Variant deflate_add(const Variant &context, const Variant &data, const Variant &flush_mode = 2);
Variant inflate_init(const Variant &encoding, const Variant &options = Array{});
Variant inflate_add(const Variant &context, const Variant &data, const Variant &flush_mode = 2);
Variant inflate_get_status(const Variant &context);
Variant inflate_get_read_len(const Variant &context);
}
