namespace php {
extern Variant LIBXML_VERSION;
extern Variant LIBXML_DOTTED_VERSION;
extern Variant LIBXML_LOADED_VERSION;
extern Variant LIBXML_NOENT;
extern Variant LIBXML_DTDLOAD;
extern Variant LIBXML_DTDATTR;
extern Variant LIBXML_DTDVALID;
extern Variant LIBXML_NOERROR;
extern Variant LIBXML_NOWARNING;
extern Variant LIBXML_NOBLANKS;
extern Variant LIBXML_XINCLUDE;
extern Variant LIBXML_NSCLEAN;
extern Variant LIBXML_NOCDATA;
extern Variant LIBXML_NONET;
extern Variant LIBXML_PEDANTIC;
extern Variant LIBXML_COMPACT;
extern Variant LIBXML_NOXMLDECL;
extern Variant LIBXML_PARSEHUGE;
extern Variant LIBXML_BIGLINES;
extern Variant LIBXML_NOEMPTYTAG;
extern Variant LIBXML_SCHEMA_CREATE;
extern Variant LIBXML_HTML_NOIMPLIED;
extern Variant LIBXML_HTML_NODEFDTD;
extern Variant LIBXML_ERR_NONE;
extern Variant LIBXML_ERR_WARNING;
extern Variant LIBXML_ERR_ERROR;
extern Variant LIBXML_ERR_FATAL;
}
