namespace php {
extern Variant POSIX_F_OK;
extern Variant POSIX_X_OK;
extern Variant POSIX_W_OK;
extern Variant POSIX_R_OK;
extern Variant POSIX_S_IFREG;
extern Variant POSIX_S_IFCHR;
extern Variant POSIX_S_IFBLK;
extern Variant POSIX_S_IFIFO;
extern Variant POSIX_S_IFSOCK;
extern Variant POSIX_RLIMIT_AS;
extern Variant POSIX_RLIMIT_CORE;
extern Variant POSIX_RLIMIT_CPU;
extern Variant POSIX_RLIMIT_DATA;
extern Variant POSIX_RLIMIT_FSIZE;
extern Variant POSIX_RLIMIT_LOCKS;
extern Variant POSIX_RLIMIT_MEMLOCK;
extern Variant POSIX_RLIMIT_MSGQUEUE;
extern Variant POSIX_RLIMIT_NICE;
extern Variant POSIX_RLIMIT_NOFILE;
extern Variant POSIX_RLIMIT_NPROC;
extern Variant POSIX_RLIMIT_RSS;
extern Variant POSIX_RLIMIT_RTPRIO;
extern Variant POSIX_RLIMIT_RTTIME;
extern Variant POSIX_RLIMIT_SIGPENDING;
extern Variant POSIX_RLIMIT_STACK;
extern Variant POSIX_RLIMIT_INFINITY;
}
