namespace php {
extern Variant FORCE_GZIP;
extern Variant FORCE_DEFLATE;
extern Variant ZLIB_ENCODING_RAW;
extern Variant ZLIB_ENCODING_GZIP;
extern Variant ZLIB_ENCODING_DEFLATE;
extern Variant ZLIB_NO_FLUSH;
extern Variant ZLIB_PARTIAL_FLUSH;
extern Variant ZLIB_SYNC_FLUSH;
extern Variant ZLIB_FULL_FLUSH;
extern Variant ZLIB_BLOCK;
extern Variant ZLIB_FINISH;
extern Variant ZLIB_FILTERED;
extern Variant ZLIB_HUFFMAN_ONLY;
extern Variant ZLIB_RLE;
extern Variant ZLIB_FIXED;
extern Variant ZLIB_DEFAULT_STRATEGY;
extern Variant ZLIB_VERSION;
extern Variant ZLIB_VERNUM;
extern Variant ZLIB_OK;
extern Variant ZLIB_STREAM_END;
extern Variant ZLIB_NEED_DICT;
extern Variant ZLIB_ERRNO;
extern Variant ZLIB_STREAM_ERROR;
extern Variant ZLIB_DATA_ERROR;
extern Variant ZLIB_MEM_ERROR;
extern Variant ZLIB_BUF_ERROR;
extern Variant ZLIB_VERSION_ERROR;
}
