/*
  +----------------------------------------------------------------------+
  | PHP-X                                                                |
  +----------------------------------------------------------------------+
  | This source file is subject to version 2.0 of the Apache license,    |
  | that is bundled with this package in the file LICENSE, and is        |
  | available through the world-wide-web at the following url:           |
  | http://www.apache.org/licenses/LICENSE-2.0.html                      |
  | If you did not receive a copy of the Apache2.0 license and are unable|
  | to obtain it through the world-wide-web, please send a note to       |
  | license@swoole.com so we can mail you a copy immediately.            |
  +----------------------------------------------------------------------+
  | Author: Tianfeng Han  <rango@swoole.com>                             |
  +----------------------------------------------------------------------+
*/

#pragma once

#include "phpx.h"

/** extension bcmath */
namespace php {
extern Variant bcadd;
extern Variant bcsub;
extern Variant bcmul;
extern Variant bcdiv;
extern Variant bcmod;
extern Variant bcpowmod;
extern Variant bcpow;
extern Variant bcsqrt;
extern Variant bccomp;
extern Variant bcscale;
}

/** extension Core */
namespace php {
extern Variant zend_version;
extern Variant func_num_args;
extern Variant func_get_arg;
extern Variant func_get_args;
extern Variant strlen;
extern Variant strcmp;
extern Variant strncmp;
extern Variant strcasecmp;
extern Variant strncasecmp;
extern Variant error_reporting;
extern Variant defined;
extern Variant get_class;
extern Variant get_called_class;
extern Variant get_parent_class;
extern Variant is_subclass_of;
extern Variant is_a;
extern Variant get_class_vars;
extern Variant get_object_vars;
extern Variant get_mangled_object_vars;
extern Variant get_class_methods;
extern Variant method_exists;
extern Variant property_exists;
extern Variant class_exists;
extern Variant interface_exists;
extern Variant trait_exists;
extern Variant enum_exists;
extern Variant function_exists;
extern Variant class_alias;
extern Variant get_included_files;
extern Variant get_required_files;
extern Variant trigger_error;
extern Variant user_error;
extern Variant set_error_handler;
extern Variant restore_error_handler;
extern Variant set_exception_handler;
extern Variant restore_exception_handler;
extern Variant get_declared_classes;
extern Variant get_declared_traits;
extern Variant get_declared_interfaces;
extern Variant get_defined_functions;
extern Variant get_defined_vars;
extern Variant get_resource_type;
extern Variant get_resource_id;
extern Variant get_resources;
extern Variant get_loaded_extensions;
extern Variant get_defined_constants;
extern Variant debug_backtrace;
extern Variant debug_print_backtrace;
extern Variant extension_loaded;
extern Variant get_extension_funcs;
extern Variant zend_thread_id;
extern Variant gc_mem_caches;
extern Variant gc_collect_cycles;
extern Variant gc_enabled;
extern Variant gc_enable;
extern Variant gc_disable;
extern Variant gc_status;
}

/** extension ctype */
namespace php {
extern Variant ctype_alnum;
extern Variant ctype_alpha;
extern Variant ctype_cntrl;
extern Variant ctype_digit;
extern Variant ctype_lower;
extern Variant ctype_graph;
extern Variant ctype_print;
extern Variant ctype_punct;
extern Variant ctype_space;
extern Variant ctype_upper;
extern Variant ctype_xdigit;
}

/** extension curl */
namespace php {
extern Variant curl_close;
extern Variant curl_copy_handle;
extern Variant curl_errno;
extern Variant curl_error;
extern Variant curl_escape;
extern Variant curl_unescape;
extern Variant curl_multi_setopt;
extern Variant curl_exec;
extern Variant curl_file_create;
extern Variant curl_getinfo;
extern Variant curl_init;
extern Variant curl_upkeep;
extern Variant curl_multi_add_handle;
extern Variant curl_multi_close;
extern Variant curl_multi_errno;
extern Variant curl_multi_exec;
extern Variant curl_multi_getcontent;
extern Variant curl_multi_info_read;
extern Variant curl_multi_init;
extern Variant curl_multi_remove_handle;
extern Variant curl_multi_select;
extern Variant curl_multi_strerror;
extern Variant curl_pause;
extern Variant curl_reset;
extern Variant curl_setopt_array;
extern Variant curl_setopt;
extern Variant curl_share_close;
extern Variant curl_share_errno;
extern Variant curl_share_init;
extern Variant curl_share_setopt;
extern Variant curl_share_strerror;
extern Variant curl_strerror;
extern Variant curl_version;
}

/** extension date */
namespace php {
extern Variant strtotime;
extern Variant date;
extern Variant idate;
extern Variant gmdate;
extern Variant mktime;
extern Variant gmmktime;
extern Variant checkdate;
extern Variant strftime;
extern Variant gmstrftime;
extern Variant time;
extern Variant localtime;
extern Variant getdate;
extern Variant date_create;
extern Variant date_create_immutable;
extern Variant date_create_from_format;
extern Variant date_create_immutable_from_format;
extern Variant date_parse;
extern Variant date_parse_from_format;
extern Variant date_get_last_errors;
extern Variant date_format;
extern Variant date_modify;
extern Variant date_add;
extern Variant date_sub;
extern Variant date_timezone_get;
extern Variant date_timezone_set;
extern Variant date_offset_get;
extern Variant date_diff;
extern Variant date_time_set;
extern Variant date_date_set;
extern Variant date_isodate_set;
extern Variant date_timestamp_set;
extern Variant date_timestamp_get;
extern Variant timezone_open;
extern Variant timezone_name_get;
extern Variant timezone_name_from_abbr;
extern Variant timezone_offset_get;
extern Variant timezone_transitions_get;
extern Variant timezone_location_get;
extern Variant timezone_identifiers_list;
extern Variant timezone_abbreviations_list;
extern Variant timezone_version_get;
extern Variant date_interval_create_from_date_string;
extern Variant date_interval_format;
extern Variant date_default_timezone_set;
extern Variant date_default_timezone_get;
extern Variant date_sunrise;
extern Variant date_sunset;
extern Variant date_sun_info;
}

/** extension dom */
namespace php {
extern Variant dom_import_simplexml;
}

/** extension exif */
namespace php {
extern Variant exif_tagname;
extern Variant exif_read_data;
extern Variant exif_thumbnail;
extern Variant exif_imagetype;
}

/** extension fileinfo */
namespace php {
extern Variant finfo_open;
extern Variant finfo_close;
extern Variant finfo_set_flags;
extern Variant finfo_file;
extern Variant finfo_buffer;
extern Variant mime_content_type;
}

/** extension filter */
namespace php {
extern Variant filter_has_var;
extern Variant filter_input;
extern Variant filter_var;
extern Variant filter_input_array;
extern Variant filter_var_array;
extern Variant filter_list;
extern Variant filter_id;
}

/** extension gd */
namespace php {
extern Variant gd_info;
extern Variant imageloadfont;
extern Variant imagesetstyle;
extern Variant imagecreatetruecolor;
extern Variant imageistruecolor;
extern Variant imagetruecolortopalette;
extern Variant imagepalettetotruecolor;
extern Variant imagecolormatch;
extern Variant imagesetthickness;
extern Variant imagefilledellipse;
extern Variant imagefilledarc;
extern Variant imagealphablending;
extern Variant imagesavealpha;
extern Variant imagelayereffect;
extern Variant imagecolorallocatealpha;
extern Variant imagecolorresolvealpha;
extern Variant imagecolorclosestalpha;
extern Variant imagecolorexactalpha;
extern Variant imagecopyresampled;
extern Variant imagerotate;
extern Variant imagesettile;
extern Variant imagesetbrush;
extern Variant imagecreate;
extern Variant imagetypes;
extern Variant imagecreatefromstring;
extern Variant imagecreatefromgif;
extern Variant imagecreatefromjpeg;
extern Variant imagecreatefrompng;
extern Variant imagecreatefromwebp;
extern Variant imagecreatefromxbm;
extern Variant imagecreatefromwbmp;
extern Variant imagecreatefromgd;
extern Variant imagecreatefromgd2;
extern Variant imagecreatefromgd2part;
extern Variant imagecreatefrombmp;
extern Variant imagecreatefromtga;
extern Variant imagexbm;
extern Variant imagegif;
extern Variant imagepng;
extern Variant imagewebp;
extern Variant imagejpeg;
extern Variant imagewbmp;
extern Variant imagegd;
extern Variant imagegd2;
extern Variant imagebmp;
extern Variant imagedestroy;
extern Variant imagecolorallocate;
extern Variant imagepalettecopy;
extern Variant imagecolorat;
extern Variant imagecolorclosest;
extern Variant imagecolorclosesthwb;
extern Variant imagecolordeallocate;
extern Variant imagecolorresolve;
extern Variant imagecolorexact;
extern Variant imagecolorset;
extern Variant imagecolorsforindex;
extern Variant imagegammacorrect;
extern Variant imagesetpixel;
extern Variant imageline;
extern Variant imagedashedline;
extern Variant imagerectangle;
extern Variant imagefilledrectangle;
extern Variant imagearc;
extern Variant imageellipse;
extern Variant imagefilltoborder;
extern Variant imagefill;
extern Variant imagecolorstotal;
extern Variant imagecolortransparent;
extern Variant imageinterlace;
extern Variant imagepolygon;
extern Variant imageopenpolygon;
extern Variant imagefilledpolygon;
extern Variant imagefontwidth;
extern Variant imagefontheight;
extern Variant imagechar;
extern Variant imagecharup;
extern Variant imagestring;
extern Variant imagestringup;
extern Variant imagecopy;
extern Variant imagecopymerge;
extern Variant imagecopymergegray;
extern Variant imagecopyresized;
extern Variant imagesx;
extern Variant imagesy;
extern Variant imagesetclip;
extern Variant imagegetclip;
extern Variant imagefilter;
extern Variant imageconvolution;
extern Variant imageflip;
extern Variant imageantialias;
extern Variant imagecrop;
extern Variant imagecropauto;
extern Variant imagescale;
extern Variant imageaffine;
extern Variant imageaffinematrixget;
extern Variant imageaffinematrixconcat;
extern Variant imagegetinterpolation;
extern Variant imagesetinterpolation;
extern Variant imageresolution;
}

/** extension hash */
namespace php {
extern Variant hash_file;
extern Variant hash_hmac_file;
extern Variant hash_init;
extern Variant hash_update;
extern Variant hash_update_stream;
extern Variant hash_update_file;
extern Variant hash_final;
extern Variant hash_copy;
extern Variant hash_algos;
extern Variant hash_hmac_algos;
extern Variant hash_pbkdf2;
extern Variant hash_equals;
extern Variant hash_hkdf;
}

/** extension iconv */
namespace php {
extern Variant iconv_strlen;
extern Variant iconv_substr;
extern Variant iconv_strpos;
extern Variant iconv_strrpos;
extern Variant iconv_mime_encode;
extern Variant iconv_mime_decode;
extern Variant iconv_mime_decode_headers;
extern Variant iconv;
extern Variant iconv_set_encoding;
extern Variant iconv_get_encoding;
}

/** extension json */
namespace php {
extern Variant json_encode;
extern Variant json_decode;
extern Variant json_last_error;
extern Variant json_last_error_msg;
}

/** extension libxml */
namespace php {
extern Variant libxml_set_streams_context;
extern Variant libxml_use_internal_errors;
extern Variant libxml_get_last_error;
extern Variant libxml_get_errors;
extern Variant libxml_clear_errors;
extern Variant libxml_disable_entity_loader;
extern Variant libxml_set_external_entity_loader;
extern Variant libxml_get_external_entity_loader;
}

/** extension mbstring */
namespace php {
extern Variant mb_language;
extern Variant mb_internal_encoding;
extern Variant mb_http_input;
extern Variant mb_http_output;
extern Variant mb_detect_order;
extern Variant mb_substitute_character;
extern Variant mb_preferred_mime_name;
extern Variant mb_parse_str;
extern Variant mb_output_handler;
extern Variant mb_str_split;
extern Variant mb_strlen;
extern Variant mb_strpos;
extern Variant mb_strrpos;
extern Variant mb_stripos;
extern Variant mb_strripos;
extern Variant mb_strstr;
extern Variant mb_strrchr;
extern Variant mb_stristr;
extern Variant mb_strrichr;
extern Variant mb_substr_count;
extern Variant mb_substr;
extern Variant mb_strcut;
extern Variant mb_strwidth;
extern Variant mb_strimwidth;
extern Variant mb_convert_encoding;
extern Variant mb_convert_case;
extern Variant mb_strtoupper;
extern Variant mb_strtolower;
extern Variant mb_detect_encoding;
extern Variant mb_list_encodings;
extern Variant mb_encoding_aliases;
extern Variant mb_encode_mimeheader;
extern Variant mb_decode_mimeheader;
extern Variant mb_convert_kana;
extern Variant mb_convert_variables;
extern Variant mb_encode_numericentity;
extern Variant mb_decode_numericentity;
extern Variant mb_send_mail;
extern Variant mb_get_info;
extern Variant mb_check_encoding;
extern Variant mb_scrub;
extern Variant mb_ord;
extern Variant mb_chr;
extern Variant mb_regex_encoding;
extern Variant mb_ereg;
extern Variant mb_eregi;
extern Variant mb_ereg_replace;
extern Variant mb_eregi_replace;
extern Variant mb_ereg_replace_callback;
extern Variant mb_split;
extern Variant mb_ereg_match;
extern Variant mb_ereg_search;
extern Variant mb_ereg_search_pos;
extern Variant mb_ereg_search_regs;
extern Variant mb_ereg_search_init;
extern Variant mb_ereg_search_getregs;
extern Variant mb_ereg_search_getpos;
extern Variant mb_ereg_search_setpos;
extern Variant mb_regex_set_options;
}

/** extension openssl */
namespace php {
extern Variant openssl_x509_export_to_file;
extern Variant openssl_x509_export;
extern Variant openssl_x509_fingerprint;
extern Variant openssl_x509_check_private_key;
extern Variant openssl_x509_verify;
extern Variant openssl_x509_parse;
extern Variant openssl_x509_checkpurpose;
extern Variant openssl_x509_read;
extern Variant openssl_x509_free;
extern Variant openssl_pkcs12_export_to_file;
extern Variant openssl_pkcs12_export;
extern Variant openssl_pkcs12_read;
extern Variant openssl_csr_export_to_file;
extern Variant openssl_csr_export;
extern Variant openssl_csr_sign;
extern Variant openssl_csr_new;
extern Variant openssl_csr_get_subject;
extern Variant openssl_csr_get_public_key;
extern Variant openssl_pkey_new;
extern Variant openssl_pkey_export_to_file;
extern Variant openssl_pkey_export;
extern Variant openssl_pkey_get_public;
extern Variant openssl_get_publickey;
extern Variant openssl_pkey_free;
extern Variant openssl_free_key;
extern Variant openssl_pkey_get_private;
extern Variant openssl_get_privatekey;
extern Variant openssl_pkey_get_details;
extern Variant openssl_pbkdf2;
extern Variant openssl_pkcs7_verify;
extern Variant openssl_pkcs7_encrypt;
extern Variant openssl_pkcs7_sign;
extern Variant openssl_pkcs7_decrypt;
extern Variant openssl_pkcs7_read;
extern Variant openssl_cms_verify;
extern Variant openssl_cms_encrypt;
extern Variant openssl_cms_sign;
extern Variant openssl_cms_decrypt;
extern Variant openssl_cms_read;
extern Variant openssl_private_encrypt;
extern Variant openssl_private_decrypt;
extern Variant openssl_public_encrypt;
extern Variant openssl_public_decrypt;
extern Variant openssl_error_string;
extern Variant openssl_sign;
extern Variant openssl_verify;
extern Variant openssl_seal;
extern Variant openssl_open;
extern Variant openssl_get_md_methods;
extern Variant openssl_get_cipher_methods;
extern Variant openssl_get_curve_names;
extern Variant openssl_digest;
extern Variant openssl_encrypt;
extern Variant openssl_decrypt;
extern Variant openssl_cipher_iv_length;
extern Variant openssl_cipher_key_length;
extern Variant openssl_dh_compute_key;
extern Variant openssl_pkey_derive;
extern Variant openssl_random_pseudo_bytes;
extern Variant openssl_spki_new;
extern Variant openssl_spki_verify;
extern Variant openssl_spki_export;
extern Variant openssl_spki_export_challenge;
extern Variant openssl_get_cert_locations;
}

/** extension pcntl */
namespace php {
extern Variant pcntl_fork;
extern Variant pcntl_waitpid;
extern Variant pcntl_wait;
extern Variant pcntl_signal;
extern Variant pcntl_signal_get_handler;
extern Variant pcntl_signal_dispatch;
extern Variant pcntl_sigprocmask;
extern Variant pcntl_sigwaitinfo;
extern Variant pcntl_sigtimedwait;
extern Variant pcntl_wifexited;
extern Variant pcntl_wifstopped;
extern Variant pcntl_wifcontinued;
extern Variant pcntl_wifsignaled;
extern Variant pcntl_wexitstatus;
extern Variant pcntl_wtermsig;
extern Variant pcntl_wstopsig;
extern Variant pcntl_exec;
extern Variant pcntl_alarm;
extern Variant pcntl_get_last_error;
extern Variant pcntl_errno;
extern Variant pcntl_getpriority;
extern Variant pcntl_setpriority;
extern Variant pcntl_strerror;
extern Variant pcntl_async_signals;
extern Variant pcntl_unshare;
}

/** extension pcre */
namespace php {
extern Variant preg_match;
extern Variant preg_match_all;
extern Variant preg_replace;
extern Variant preg_filter;
extern Variant preg_replace_callback;
extern Variant preg_replace_callback_array;
extern Variant preg_split;
extern Variant preg_quote;
extern Variant preg_grep;
extern Variant preg_last_error;
extern Variant preg_last_error_msg;
}

/** extension PDO */
namespace php {
extern Variant pdo_drivers;
}

/** extension posix */
namespace php {
extern Variant posix_kill;
extern Variant posix_getpid;
extern Variant posix_getppid;
extern Variant posix_getuid;
extern Variant posix_setuid;
extern Variant posix_geteuid;
extern Variant posix_seteuid;
extern Variant posix_getgid;
extern Variant posix_setgid;
extern Variant posix_getegid;
extern Variant posix_setegid;
extern Variant posix_getgroups;
extern Variant posix_getlogin;
extern Variant posix_getpgrp;
extern Variant posix_setsid;
extern Variant posix_setpgid;
extern Variant posix_getpgid;
extern Variant posix_getsid;
extern Variant posix_uname;
extern Variant posix_times;
extern Variant posix_ctermid;
extern Variant posix_ttyname;
extern Variant posix_isatty;
extern Variant posix_getcwd;
extern Variant posix_mkfifo;
extern Variant posix_mknod;
extern Variant posix_access;
extern Variant posix_getgrnam;
extern Variant posix_getgrgid;
extern Variant posix_getpwnam;
extern Variant posix_getpwuid;
extern Variant posix_getrlimit;
extern Variant posix_setrlimit;
extern Variant posix_get_last_error;
extern Variant posix_errno;
extern Variant posix_strerror;
extern Variant posix_initgroups;
}

/** extension random */
namespace php {
extern Variant lcg_value;
extern Variant mt_srand;
extern Variant srand;
extern Variant rand;
extern Variant mt_rand;
extern Variant mt_getrandmax;
extern Variant getrandmax;
extern Variant random_bytes;
extern Variant random_int;
}

/** extension session */
namespace php {
extern Variant session_name;
extern Variant session_module_name;
extern Variant session_save_path;
extern Variant session_id;
extern Variant session_create_id;
extern Variant session_regenerate_id;
extern Variant session_decode;
extern Variant session_encode;
extern Variant session_destroy;
extern Variant session_unset;
extern Variant session_gc;
extern Variant session_get_cookie_params;
extern Variant session_write_close;
extern Variant session_abort;
extern Variant session_reset;
extern Variant session_status;
extern Variant session_register_shutdown;
extern Variant session_commit;
extern Variant session_set_save_handler;
extern Variant session_cache_limiter;
extern Variant session_cache_expire;
extern Variant session_set_cookie_params;
extern Variant session_start;
}

/** extension SimpleXML */
namespace php {
extern Variant simplexml_load_file;
extern Variant simplexml_load_string;
extern Variant simplexml_import_dom;
}

/** extension sockets */
namespace php {
extern Variant socket_select;
extern Variant socket_create_listen;
extern Variant socket_accept;
extern Variant socket_set_nonblock;
extern Variant socket_set_block;
extern Variant socket_listen;
extern Variant socket_close;
extern Variant socket_write;
extern Variant socket_read;
extern Variant socket_getsockname;
extern Variant socket_getpeername;
extern Variant socket_create;
extern Variant socket_connect;
extern Variant socket_strerror;
extern Variant socket_bind;
extern Variant socket_recv;
extern Variant socket_send;
extern Variant socket_recvfrom;
extern Variant socket_sendto;
extern Variant socket_get_option;
extern Variant socket_getopt;
extern Variant socket_set_option;
extern Variant socket_setopt;
extern Variant socket_create_pair;
extern Variant socket_shutdown;
extern Variant socket_last_error;
extern Variant socket_clear_error;
extern Variant socket_import_stream;
extern Variant socket_export_stream;
extern Variant socket_sendmsg;
extern Variant socket_recvmsg;
extern Variant socket_cmsg_space;
extern Variant socket_addrinfo_lookup;
extern Variant socket_addrinfo_connect;
extern Variant socket_addrinfo_bind;
extern Variant socket_addrinfo_explain;
}

/** extension SPL */
namespace php {
extern Variant class_implements;
extern Variant class_parents;
extern Variant class_uses;
extern Variant spl_autoload;
extern Variant spl_autoload_call;
extern Variant spl_autoload_extensions;
extern Variant spl_autoload_functions;
extern Variant spl_autoload_register;
extern Variant spl_autoload_unregister;
extern Variant spl_classes;
extern Variant spl_object_hash;
extern Variant spl_object_id;
extern Variant iterator_apply;
extern Variant iterator_count;
extern Variant iterator_to_array;
}

/** extension standard */
namespace php {
extern Variant set_time_limit;
extern Variant header_register_callback;
extern Variant ob_start;
extern Variant ob_flush;
extern Variant ob_clean;
extern Variant ob_end_flush;
extern Variant ob_end_clean;
extern Variant ob_get_flush;
extern Variant ob_get_clean;
extern Variant ob_get_contents;
extern Variant ob_get_level;
extern Variant ob_get_length;
extern Variant ob_list_handlers;
extern Variant ob_get_status;
extern Variant ob_implicit_flush;
extern Variant output_reset_rewrite_vars;
extern Variant output_add_rewrite_var;
extern Variant stream_wrapper_register;
extern Variant stream_register_wrapper;
extern Variant stream_wrapper_unregister;
extern Variant stream_wrapper_restore;
extern Variant array_push;
extern Variant krsort;
extern Variant ksort;
extern Variant count;
extern Variant natsort;
extern Variant natcasesort;
extern Variant asort;
extern Variant arsort;
extern Variant sort;
extern Variant rsort;
extern Variant usort;
extern Variant uasort;
extern Variant uksort;
extern Variant end;
extern Variant prev;
extern Variant next;
extern Variant reset;
extern Variant current;
extern Variant pos;
extern Variant key;
extern Variant min;
extern Variant max;
extern Variant array_walk;
extern Variant array_walk_recursive;
extern Variant in_array;
extern Variant array_search;
extern Variant extract;
extern Variant compact;
extern Variant array_fill;
extern Variant array_fill_keys;
extern Variant range;
extern Variant shuffle;
extern Variant array_pop;
extern Variant array_shift;
extern Variant array_unshift;
extern Variant array_splice;
extern Variant array_slice;
extern Variant array_merge;
extern Variant array_merge_recursive;
extern Variant array_replace;
extern Variant array_replace_recursive;
extern Variant array_keys;
extern Variant array_key_first;
extern Variant array_key_last;
extern Variant array_values;
extern Variant array_count_values;
extern Variant array_column;
extern Variant array_reverse;
extern Variant array_pad;
extern Variant array_flip;
extern Variant array_change_key_case;
extern Variant array_unique;
extern Variant array_intersect_key;
extern Variant array_intersect_ukey;
extern Variant array_intersect;
extern Variant array_uintersect;
extern Variant array_intersect_assoc;
extern Variant array_uintersect_assoc;
extern Variant array_intersect_uassoc;
extern Variant array_uintersect_uassoc;
extern Variant array_diff_key;
extern Variant array_diff_ukey;
extern Variant array_diff;
extern Variant array_udiff;
extern Variant array_diff_assoc;
extern Variant array_diff_uassoc;
extern Variant array_udiff_assoc;
extern Variant array_udiff_uassoc;
extern Variant array_multisort;
extern Variant array_rand;
extern Variant array_sum;
extern Variant array_product;
extern Variant array_reduce;
extern Variant array_filter;
extern Variant array_map;
extern Variant array_key_exists;
extern Variant key_exists;
extern Variant array_chunk;
extern Variant array_combine;
extern Variant array_is_list;
extern Variant base64_encode;
extern Variant base64_decode;
extern Variant ip2long;
extern Variant long2ip;
extern Variant getenv;
extern Variant putenv;
extern Variant getopt;
extern Variant flush;
extern Variant sleep;
extern Variant usleep;
extern Variant time_nanosleep;
extern Variant time_sleep_until;
extern Variant get_current_user;
extern Variant get_cfg_var;
extern Variant error_log;
extern Variant error_get_last;
extern Variant error_clear_last;
extern Variant call_user_func;
extern Variant call_user_func_array;
extern Variant forward_static_call;
extern Variant forward_static_call_array;
extern Variant register_shutdown_function;
extern Variant highlight_file;
extern Variant show_source;
extern Variant php_strip_whitespace;
extern Variant highlight_string;
extern Variant ini_get_all;
extern Variant ini_set;
extern Variant ini_alter;
extern Variant ini_restore;
extern Variant ini_parse_quantity;
extern Variant set_include_path;
extern Variant get_include_path;
extern Variant print_r;
extern Variant connection_aborted;
extern Variant connection_status;
extern Variant ignore_user_abort;
extern Variant getservbyname;
extern Variant getservbyport;
extern Variant getprotobyname;
extern Variant getprotobynumber;
extern Variant register_tick_function;
extern Variant unregister_tick_function;
extern Variant is_uploaded_file;
extern Variant move_uploaded_file;
extern Variant parse_ini_file;
extern Variant parse_ini_string;
extern Variant config_get_hash;
extern Variant sys_getloadavg;
extern Variant get_browser;
extern Variant crypt;
extern Variant strptime;
extern Variant gethostname;
extern Variant gethostbyaddr;
extern Variant gethostbyname;
extern Variant gethostbynamel;
extern Variant dns_check_record;
extern Variant checkdnsrr;
extern Variant dns_get_record;
extern Variant dns_get_mx;
extern Variant getmxrr;
extern Variant net_get_interfaces;
extern Variant ftok;
extern Variant hrtime;
extern Variant md5_file;
extern Variant getmyuid;
extern Variant getmygid;
extern Variant getmypid;
extern Variant getmyinode;
extern Variant getlastmod;
extern Variant sha1_file;
extern Variant openlog;
extern Variant closelog;
extern Variant syslog;
extern Variant inet_ntop;
extern Variant inet_pton;
extern Variant metaphone;
extern Variant header;
extern Variant header_remove;
extern Variant setrawcookie;
extern Variant setcookie;
extern Variant http_response_code;
extern Variant headers_sent;
extern Variant headers_list;
extern Variant htmlspecialchars;
extern Variant htmlspecialchars_decode;
extern Variant html_entity_decode;
extern Variant htmlentities;
extern Variant get_html_translation_table;
extern Variant assert;
extern Variant assert_options;
extern Variant bin2hex;
extern Variant hex2bin;
extern Variant strspn;
extern Variant strcspn;
extern Variant nl_langinfo;
extern Variant strcoll;
extern Variant trim;
extern Variant rtrim;
extern Variant chop;
extern Variant ltrim;
extern Variant wordwrap;
extern Variant explode;
extern Variant implode;
extern Variant join;
extern Variant strtok;
extern Variant strtoupper;
extern Variant strtolower;
extern Variant basename;
extern Variant dirname;
extern Variant pathinfo;
extern Variant stristr;
extern Variant strstr;
extern Variant strchr;
extern Variant strpos;
extern Variant stripos;
extern Variant strrpos;
extern Variant strripos;
extern Variant strrchr;
extern Variant str_contains;
extern Variant str_starts_with;
extern Variant str_ends_with;
extern Variant chunk_split;
extern Variant substr;
extern Variant substr_replace;
extern Variant quotemeta;
extern Variant ord;
extern Variant chr;
extern Variant ucfirst;
extern Variant lcfirst;
extern Variant ucwords;
extern Variant strtr;
extern Variant strrev;
extern Variant similar_text;
extern Variant addcslashes;
extern Variant addslashes;
extern Variant stripcslashes;
extern Variant stripslashes;
extern Variant str_replace;
extern Variant str_ireplace;
extern Variant hebrev;
extern Variant nl2br;
extern Variant strip_tags;
extern Variant setlocale;
extern Variant parse_str;
extern Variant str_getcsv;
extern Variant str_repeat;
extern Variant count_chars;
extern Variant strnatcmp;
extern Variant localeconv;
extern Variant strnatcasecmp;
extern Variant substr_count;
extern Variant str_pad;
extern Variant sscanf;
extern Variant str_rot13;
extern Variant str_shuffle;
extern Variant str_word_count;
extern Variant str_split;
extern Variant strpbrk;
extern Variant substr_compare;
extern Variant utf8_encode;
extern Variant utf8_decode;
extern Variant opendir;
extern Variant dir;
extern Variant closedir;
extern Variant chdir;
extern Variant getcwd;
extern Variant rewinddir;
extern Variant readdir;
extern Variant scandir;
extern Variant glob;
extern Variant system;
extern Variant passthru;
extern Variant escapeshellcmd;
extern Variant escapeshellarg;
extern Variant shell_exec;
extern Variant proc_nice;
extern Variant flock;
extern Variant get_meta_tags;
extern Variant pclose;
extern Variant popen;
extern Variant readfile;
extern Variant rewind;
extern Variant rmdir;
extern Variant umask;
extern Variant fclose;
extern Variant feof;
extern Variant fgetc;
extern Variant fgets;
extern Variant fread;
extern Variant fopen;
extern Variant fscanf;
extern Variant fpassthru;
extern Variant ftruncate;
extern Variant fstat;
extern Variant fseek;
extern Variant ftell;
extern Variant fflush;
extern Variant fsync;
extern Variant fdatasync;
extern Variant fwrite;
extern Variant fputs;
extern Variant mkdir;
extern Variant rename;
extern Variant copy;
extern Variant tempnam;
extern Variant tmpfile;
extern Variant file;
extern Variant file_get_contents;
extern Variant unlink;
extern Variant file_put_contents;
extern Variant fputcsv;
extern Variant fgetcsv;
extern Variant realpath;
extern Variant fnmatch;
extern Variant sys_get_temp_dir;
extern Variant fileatime;
extern Variant filectime;
extern Variant filegroup;
extern Variant fileinode;
extern Variant filemtime;
extern Variant fileowner;
extern Variant fileperms;
extern Variant filesize;
extern Variant filetype;
extern Variant file_exists;
extern Variant is_writable;
extern Variant is_writeable;
extern Variant is_readable;
extern Variant is_executable;
extern Variant is_file;
extern Variant is_dir;
extern Variant is_link;
extern Variant stat;
extern Variant lstat;
extern Variant chown;
extern Variant chgrp;
extern Variant lchown;
extern Variant lchgrp;
extern Variant chmod;
extern Variant touch;
extern Variant clearstatcache;
extern Variant disk_total_space;
extern Variant disk_free_space;
extern Variant diskfreespace;
extern Variant realpath_cache_get;
extern Variant realpath_cache_size;
extern Variant sprintf;
extern Variant printf;
extern Variant vprintf;
extern Variant vsprintf;
extern Variant fprintf;
extern Variant vfprintf;
extern Variant fsockopen;
extern Variant pfsockopen;
extern Variant http_build_query;
extern Variant image_type_to_mime_type;
extern Variant image_type_to_extension;
extern Variant getimagesize;
extern Variant getimagesizefromstring;
extern Variant phpinfo;
extern Variant phpversion;
extern Variant phpcredits;
extern Variant php_sapi_name;
extern Variant php_uname;
extern Variant php_ini_scanned_files;
extern Variant php_ini_loaded_file;
extern Variant iptcembed;
extern Variant iptcparse;
extern Variant levenshtein;
extern Variant readlink;
extern Variant linkinfo;
extern Variant symlink;
extern Variant link;
extern Variant mail;
extern Variant abs;
extern Variant ceil;
extern Variant floor;
extern Variant round;
extern Variant sin;
extern Variant cos;
extern Variant tan;
extern Variant asin;
extern Variant acos;
extern Variant atan;
extern Variant atanh;
extern Variant atan2;
extern Variant sinh;
extern Variant cosh;
extern Variant tanh;
extern Variant asinh;
extern Variant acosh;
extern Variant expm1;
extern Variant log1p;
extern Variant pi;
extern Variant is_finite;
extern Variant is_nan;
extern Variant intdiv;
extern Variant is_infinite;
extern Variant pow;
extern Variant exp;
extern Variant log;
extern Variant log10;
extern Variant sqrt;
extern Variant hypot;
extern Variant deg2rad;
extern Variant rad2deg;
extern Variant bindec;
extern Variant hexdec;
extern Variant octdec;
extern Variant decbin;
extern Variant decoct;
extern Variant dechex;
extern Variant base_convert;
extern Variant number_format;
extern Variant fmod;
extern Variant fdiv;
extern Variant microtime;
extern Variant gettimeofday;
extern Variant getrusage;
extern Variant pack;
extern Variant unpack;
extern Variant password_get_info;
extern Variant password_hash;
extern Variant password_needs_rehash;
extern Variant password_verify;
extern Variant password_algos;
extern Variant proc_open;
extern Variant proc_close;
extern Variant proc_terminate;
extern Variant proc_get_status;
extern Variant quoted_printable_decode;
extern Variant quoted_printable_encode;
extern Variant soundex;
extern Variant stream_select;
extern Variant stream_context_create;
extern Variant stream_context_set_params;
extern Variant stream_context_get_params;
extern Variant stream_context_set_option;
extern Variant stream_context_get_options;
extern Variant stream_context_get_default;
extern Variant stream_context_set_default;
extern Variant stream_filter_prepend;
extern Variant stream_filter_append;
extern Variant stream_filter_remove;
extern Variant stream_socket_client;
extern Variant stream_socket_server;
extern Variant stream_socket_accept;
extern Variant stream_socket_get_name;
extern Variant stream_socket_recvfrom;
extern Variant stream_socket_sendto;
extern Variant stream_socket_enable_crypto;
extern Variant stream_socket_shutdown;
extern Variant stream_socket_pair;
extern Variant stream_copy_to_stream;
extern Variant stream_get_contents;
extern Variant stream_supports_lock;
extern Variant stream_set_write_buffer;
extern Variant set_file_buffer;
extern Variant stream_set_read_buffer;
extern Variant stream_set_blocking;
extern Variant socket_set_blocking;
extern Variant stream_get_meta_data;
extern Variant socket_get_status;
extern Variant stream_get_line;
extern Variant stream_resolve_include_path;
extern Variant stream_get_wrappers;
extern Variant stream_get_transports;
extern Variant stream_is_local;
extern Variant stream_isatty;
extern Variant stream_set_chunk_size;
extern Variant stream_set_timeout;
extern Variant socket_set_timeout;
extern Variant gettype;
extern Variant get_debug_type;
extern Variant settype;
extern Variant intval;
extern Variant floatval;
extern Variant doubleval;
extern Variant boolval;
extern Variant strval;
extern Variant is_null;
extern Variant is_resource;
extern Variant is_bool;
extern Variant is_int;
extern Variant is_integer;
extern Variant is_long;
extern Variant is_float;
extern Variant is_double;
extern Variant is_numeric;
extern Variant is_string;
extern Variant is_array;
extern Variant is_object;
extern Variant is_scalar;
extern Variant is_callable;
extern Variant is_iterable;
extern Variant is_countable;
extern Variant uniqid;
extern Variant parse_url;
extern Variant urlencode;
extern Variant urldecode;
extern Variant rawurlencode;
extern Variant rawurldecode;
extern Variant get_headers;
extern Variant stream_bucket_make_writeable;
extern Variant stream_bucket_prepend;
extern Variant stream_bucket_append;
extern Variant stream_bucket_new;
extern Variant stream_get_filters;
extern Variant stream_filter_register;
extern Variant convert_uuencode;
extern Variant convert_uudecode;
extern Variant var_dump;
extern Variant var_export;
extern Variant debug_zval_dump;
extern Variant serialize;
extern Variant unserialize;
extern Variant memory_get_usage;
extern Variant memory_get_peak_usage;
extern Variant memory_reset_peak_usage;
extern Variant version_compare;
extern Variant dl;
extern Variant cli_set_process_title;
extern Variant cli_get_process_title;
}

/** extension tokenizer */
namespace php {
extern Variant token_get_all;
extern Variant token_name;
}

/** extension xml */
namespace php {
extern Variant xml_parser_create;
extern Variant xml_parser_create_ns;
extern Variant xml_set_object;
extern Variant xml_set_element_handler;
extern Variant xml_set_character_data_handler;
extern Variant xml_set_processing_instruction_handler;
extern Variant xml_set_default_handler;
extern Variant xml_set_unparsed_entity_decl_handler;
extern Variant xml_set_notation_decl_handler;
extern Variant xml_set_external_entity_ref_handler;
extern Variant xml_set_start_namespace_decl_handler;
extern Variant xml_set_end_namespace_decl_handler;
extern Variant xml_parse;
extern Variant xml_parse_into_struct;
extern Variant xml_get_error_code;
extern Variant xml_error_string;
extern Variant xml_get_current_line_number;
extern Variant xml_get_current_column_number;
extern Variant xml_get_current_byte_index;
extern Variant xml_parser_free;
extern Variant xml_parser_set_option;
extern Variant xml_parser_get_option;
}

/** extension xmlwriter */
namespace php {
extern Variant xmlwriter_open_uri;
extern Variant xmlwriter_open_memory;
extern Variant xmlwriter_set_indent;
extern Variant xmlwriter_set_indent_string;
extern Variant xmlwriter_start_comment;
extern Variant xmlwriter_end_comment;
extern Variant xmlwriter_start_attribute;
extern Variant xmlwriter_end_attribute;
extern Variant xmlwriter_write_attribute;
extern Variant xmlwriter_start_attribute_ns;
extern Variant xmlwriter_write_attribute_ns;
extern Variant xmlwriter_start_element;
extern Variant xmlwriter_end_element;
extern Variant xmlwriter_full_end_element;
extern Variant xmlwriter_start_element_ns;
extern Variant xmlwriter_write_element;
extern Variant xmlwriter_write_element_ns;
extern Variant xmlwriter_start_pi;
extern Variant xmlwriter_end_pi;
extern Variant xmlwriter_write_pi;
extern Variant xmlwriter_start_cdata;
extern Variant xmlwriter_end_cdata;
extern Variant xmlwriter_write_cdata;
extern Variant xmlwriter_text;
extern Variant xmlwriter_write_raw;
extern Variant xmlwriter_start_document;
extern Variant xmlwriter_end_document;
extern Variant xmlwriter_write_comment;
extern Variant xmlwriter_start_dtd;
extern Variant xmlwriter_end_dtd;
extern Variant xmlwriter_write_dtd;
extern Variant xmlwriter_start_dtd_element;
extern Variant xmlwriter_end_dtd_element;
extern Variant xmlwriter_write_dtd_element;
extern Variant xmlwriter_start_dtd_attlist;
extern Variant xmlwriter_end_dtd_attlist;
extern Variant xmlwriter_write_dtd_attlist;
extern Variant xmlwriter_start_dtd_entity;
extern Variant xmlwriter_end_dtd_entity;
extern Variant xmlwriter_write_dtd_entity;
extern Variant xmlwriter_output_memory;
extern Variant xmlwriter_flush;
}

/** extension zlib */
namespace php {
extern Variant ob_gzhandler;
extern Variant zlib_get_coding_type;
extern Variant gzfile;
extern Variant gzopen;
extern Variant readgzfile;
extern Variant zlib_encode;
extern Variant zlib_decode;
extern Variant gzdeflate;
extern Variant gzencode;
extern Variant gzcompress;
extern Variant gzinflate;
extern Variant gzdecode;
extern Variant gzuncompress;
extern Variant gzwrite;
extern Variant gzputs;
extern Variant gzrewind;
extern Variant gzclose;
extern Variant gzeof;
extern Variant gzgetc;
extern Variant gzpassthru;
extern Variant gzseek;
extern Variant gztell;
extern Variant gzread;
extern Variant gzgets;
extern Variant deflate_init;
extern Variant deflate_add;
extern Variant inflate_init;
extern Variant inflate_add;
extern Variant inflate_get_status;
extern Variant inflate_get_read_len;
}
