#ifndef TYPEPHP_OPCODE_TABLE_H
#define TYPEPHP_OPCODE_TABLE_H

#include <stddef.h>
#include <stdint.h>

typedef struct {
    const char *path;
    const uint8_t *bytes;
    size_t length;
} typephp_opcode_entry;

typedef struct {
    const char *path;
    const uint8_t *bytes;
    size_t length;
} typephp_embedded_file_entry;

#ifdef __cplusplus
extern "C" {
#endif

/* Generated by the TypePHP compiler for each embedded executable. */
const typephp_opcode_entry *typephp_project_opcode_table(size_t *count);
const typephp_embedded_file_entry *typephp_project_embedded_file_table(size_t *count);
const char *typephp_project_php_version(void);
const char *typephp_project_entry_file(void);

#ifdef _WIN32
/* Return the bytes of the archive linked as a Windows PE resource. */
const uint8_t *typephp_embedded_archive_data(void);
#endif

void typephp_opcode_table_install(void);
void typephp_opcode_table_startup(void);
void typephp_opcode_table_request_startup(void);
void typephp_opcode_table_request_shutdown(void);
void typephp_opcode_table_shutdown(void);
int typephp_embedded_file_exists(const char *path);
/* 0: missing, 1: file, 2: directory. */
int typephp_embedded_path_kind(const char *path);
void typephp_opcode_table_require(const char *path);
void typephp_opcode_table_uninstall(void);

#ifdef __cplusplus
}
#endif

#endif
